enum ScreenID
{
    kInvalid = -1,
    kSplashScreen = 0,
    kMainScreen = 1,
    kSelectScreen = 2,
    kRandomModeScreen = 3,
    kHomeModeScreen = 4,
    kSettingsScreen = 5,
    kSetHomeScreen = 6,
    kRotateDomeScreen = 7,
    kDomeSpeedScreen = 8,
    kDomeHomeSpeedScreen = 9,
    kDomeSeekSpeedScreen = 10,
    kDomeMinSpeedScreen = 11,
    kDomeSeekLeftScreen = 12,
    kDomeSeekRightScreen = 13,
    kDomeFudgeScreen = 14,
    kDomeSeekMinDelayScreen = 15,
    kDomeSeekMaxDelayScreen = 16,
    kSetSpeedScalingScreen = 17,
    kSetInvertedScreen = 18,
    kSetAccScaleScreen = 19,
    kSetDecScaleScreen = 20,
    kSaberBaudRateScreen = 21,
    kMarcBaudRateScreen = 22,
    kPacketSerialInputScreen = 23,
    kPacketSerialOutputScreen = 24,
    kSetPWMOutputScreen = 25,
    kSetPWMInputScreen = 26,
    kSetMinPulseScreen = 27,
    kSetMaxPulseScreen = 28,
    kSetNeutralPulseScreen = 29,
    kSetDeadbandPercentScreen = 30,
    kEraseSettingsScreen = 31,
};
