enum ScreenID
{
    kInvalid = -1,
    kSplashScreen = 0,
    kMainScreen = 1,
    kSelectScreen,
    kRandomModeScreen,
    kHomeModeScreen,
    kSettingsScreen,
    kSettingsUpdatedScreen,
    kSetHomeScreen,
    kRotateDomeScreen,
    kDomeSpeedScreen,
    kDomeHomeSpeedScreen,
    kDomeAutoSpeedScreen,
    kDomeTargetSpeedScreen,
    kDomeMinSpeedScreen,
    kDomeAutoLeftScreen,
    kDomeAutoRightScreen,
    kDomeFudgeScreen,
    kDomeAutoMinDelayScreen,
    kDomeAutoMaxDelayScreen,
    kDomeHomeMaxDelayScreen,
    kDomeHomeMinDelayScreen, 
    kSetAutoSafetyScreen,
    kSaberBaudRateScreen,
    kSerialBaudRateScreen,
    kPacketSerialInputScreen,
    kPacketSerialOutputScreen,
    kSetPWMOutputScreen,
    kSetPWMInputScreen,
    kSetMinPulseScreen,
    kSetMaxPulseScreen,
    kSetNeutralPulseScreen,
    kSetDeadbandPercentScreen,
    kWiFiModeScreen,
    kEraseSettingsScreen,
};
