enum ScreenID
{
    kInvalid = -1,
    kSplashScreen = 0,
    kMainScreen = 1,
    kSelectScreen,
    kRandomModeScreen,
    kHomeModeScreen,
    kSettingsScreen,
    kSettingsUpdatedScreen,
    kSetHomeScreen,
    kRotateDomeScreen,
    kDomeSpeedScreen,
    kDomeHomeSpeedScreen,
    kDomeSeekSpeedScreen,
    kDomeTargetSpeedScreen,
    kDomeMinSpeedScreen,
    kDomeSeekLeftScreen,
    kDomeSeekRightScreen,
    kDomeFudgeScreen,
    kDomeSeekMinDelayScreen,
    kDomeSeekMaxDelayScreen,
    kDomeHomeMaxDelayScreen,
    kDomeHomeMinDelayScreen, 
    kDomeTargetMaxDelayScreen,
    kDomeTargetMinDelayScreen, 
    kSetSpeedScalingScreen,
    kSetInvertedScreen,
    kSetTimeoutScreen,
    kSetAutoSafetyScreen,
    kSetAccScaleScreen,
    kSetDecScaleScreen,
    kSaberBaudRateScreen,
    kMarcBaudRateScreen,
    kPacketSerialInputScreen,
    kPacketSerialOutputScreen,
    kSetPWMOutputScreen,
    kSetPWMInputScreen,
    kSetMinPulseScreen,
    kSetMaxPulseScreen,
    kSetNeutralPulseScreen,
    kSetDeadbandPercentScreen,
    kEraseSettingsScreen,
};
